id: IC63A70DB
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3874-final
source_file: null
initial_creation_type: input
imported: '2022-06-29T10:11:20.623541'
last_modified: '2022-06-29T10:11:20.623554'
parser: null
source_metadata:
  creation_method: proof_reading
  source : 
    base_file:
      id: D3874/འགྲེལ་བ།.txt
      initial_creation_type: input
  base:
    00A0:
      title: chonjuk commentary
      base_file: BA0D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
